spring:
  application:
    name: story-map
  datasource:
      username: root
      password: Xuan_root_123
      url: jdbc:mysql://cangwu.art:3306/story_map
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    port: 465
    password: idgxcavveinkbaeb
    username: 1533704796@qq.com
    host: smtp.qq.com
    protocol: smtp
    properties:
      from: 1533704796@qq.com
      subject: IStory-用户验证
      mail:
        smtp:
          auth: true
          ssl:
            enable: trye
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

server:
  port: 9000



